### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [jlederer2/Valkyrie#1]
Hello, jlederer2

I'm translating your scenario into Spanish. I will post here when translation were ready, to ask you to add it to the valkyrie.

**Comment by vidimus** [comment]
Hello, @jlederer2 .

Any new about updating the file with the Spanish translation?

**Comment by jlederer2** [comment]
No - but thanks for the reminder!

Jim Lederer
248-482-3668

**Comment by vidimus** [comment]
Hello, @jlederer2 
I spent a non-trivial amount of time translating the scenario because I liked it. My idea was to share this scenario with other users that could enjoy it as I did who weren't able to play in English but in Spanish. I've got no trouble with that (playing in English). I unselfishly did it for the community.
Almost 3 months have passed since I sent you the file.
So, last time I will insist on this, please, can you update the scenario with the translation?

**Comment by jlederer2** [comment]
Gosh, I’m sorry.  I will get on this tomorrow.

Jim Lederer
248-482-3668

**Comment by jlederer2** [comment]
I added the translation.  That was super easy, I'm so sorry I didn't look into this earlier.  Thanks again very much for creating the translation!

**Comment by jlederer2** [comment]
Apparently this is not working correctly.

**Comment by jlederer2** [comment]
https://github.com/NPBruce/valkyrie/issues/1317

**Comment by vidimus** [comment]
Hello, @jlederer2 
I think I've fixed the file.
Here it is:
[Localization.Spanish.txt](https://github.com/jlederer2/Valkyrie/files/4827446/Localization.Spanish.txt)

**Comment by jlederer2** [comment]
Installed and it works!
